import { TransactionHistory } from '../../app.model';

export const HISTORY_DATA: TransactionHistory[] = [
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
  {
    date: '28-05-24',
    student: 'Khurram Adhami',
    enrollment: 'NED/0719/13-14',
    department: 'Software Engg.',
    batch: '2013-14',
    blockchainProof: 'sdfsdfxxf23dsf',
    certificateId: '1bX1239',
    certificateUrl: 'https://donwload.url',
  },
];
